name: 'envsubst-action'
description: wrapper for envsubst
author: 'step-security'
branding:
  icon: 'terminal'
  color: 'yellow'
inputs:
  input:
    description: 'File to run substitutions on'
    required: true
  output:
    description: 'File to write result to'
    required: true
runs:
  using: 'docker'
  image: 'docker://ghcr.io/step-security/envsubst-action:v1.1.2@sha256:b90ed4c4dfade4f157a68308fcaa31eb6ab0d974481e64f51b4e148bfdfa36e6' #v1.1.2
