name: 'envsubst-action'
description: wrapper for envsubst
author: 'step-security'
branding:
  icon: 'terminal'
  color: 'yellow'
inputs:
  input:
    description: 'File to run substitutions on'
    required: true
  output:
    description: 'File to write result to'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
