name: 'envsubst-action'
description: wrapper for envsubst
author: 'step-security'
branding:
  icon: 'terminal'
  color: 'yellow'
inputs:
  input:
    description: 'File to run substitutions on'
    required: true
  output:
    description: 'File to write result to'
    required: true
runs:
  using: 'docker'
  image: 'docker://ghcr.io/step-security/envsubst-action:v1.1.1@sha256:84bd18d25c864f5061d093cc8bfd4cfb2ec550a198f8e3063d41a9c1aed6aadc' #v1.1.1
