name: 'envsubst-action'
description: wrapper for envsubst
author: 'step-security'
branding:
  icon: 'terminal'
  color: 'yellow'
inputs:
  input:
    description: 'File to run substitutions on'
    required: true
  output:
    description: 'File to write result to'
    required: true
runs:
  using: 'docker'
  image: 'docker://ghcr.io/step-security/envsubst-action:v1.1.3@sha256:44696c74ae3cf90816e79912ce80ee7fe51169a125033a997990663146fb36d3' #v1.1.3
